FROM ubuntu:26.04
LABEL maintainer="goetz-dev@web.de"
LABEL description="Container to build yocto images"

RUN apt-get update && \
    apt-get install -y sudo python3 python3-setuptools && \
    apt-get install -y build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping libacl1 locales python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd && \
    apt-get -y clean && \
    apt-get autoremove

RUN useradd -m yocto && \
    usermod -a -G ubuntu,users,sudo yocto && \
    echo 'yocto ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir /home/yocto/yocto && \
    mkdir /home/yocto/downloads && \
    mkdir /home/yocto/output_dir && \
    chown yocto:users /home/yocto/yocto && \
    chown yocto:users /home/yocto/downloads && \
    chown yocto:users /home/yocto/output_dir
