version: '3'

services:
  yocto_build:
    image: knallwinkel/spotypee:kirkstone
    user: yocto
    working_dir: /home/yocto
    command: bash -c "
      rm -rf yocto/* &&
      rm -rf download/* &&
      cd SpotyPee/spotypee_build &&
      source oe-init-build-env ../../yocto/build && 
      bitbake spotypee &&
      cp tmp/deploy/images/raspberrypi3-64/spotypee-raspberrypi3-64.rpi-sdimg /home/yocto/image"

    volumes:
      - build_store:/home/yocto/yocto
      - downaload_store:/home/yocto/downloads
      - ./image:/home/yocto/image
volumes:
  build_store:
  downaload_store: