version: '3'

services:
  yocto_build:
    image: knallwinkel/spotypee:honister
    user: yocto
    working_dir: /home/yocto
    volumes:
      - build_store:/home/yocto/yocto
      - downaload_store:/home/yocto/downloads
volumes:
  build_store:
  downaload_store: