services:
  yocto_build:
    image: knallwinkel/spotypee:wrynose
    user: yocto
    working_dir: /home/yocto
    volumes:
      - build_store:/home/yocto/yocto
      - downaload_store:/home/yocto/downloads
      - ./output_dir:/home/yocto/output_dir:z

volumes:
  build_store:
  downaload_store:
