name: Build Docker Container and execute them

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get current commit hash
      run: git_hash=$(git rev-parse "$GITHUB_SHA")
    - 
      name: Build Dockerfile.yocto 
      run: |
        docker build . --file Dockerfile.yocto --tag knallwinkel/yocto_kirkstone:latest
    -
      name: Build Dockerfile.SpotyPee
      run: |
        docker build . --file Dockerfile.SpotyPee --build-arg SPOTYPEE_LABEL=$git_hash --tag knallwinkel/spotypee:kirkstone
    - 
      name: Build System
      run: |
