name: Build Docker Container and execute them

on:
  push:
    branches: [ "nanbield" ]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build Dockerfile.yocto and push nanbield tag

      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.yocto
        push: true
        tags: knallwinkel/yocto_nanbield:latest
    -
      name: Build Dockerfile.SpotyPee and push nanbield tag

      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.SpotyPee
        push: true
        build-args: |
          SPOTYPEE_LABEL=nanbield
        tags: knallwinkel/spotypee:nanbield
