name: Build Docker Container and execute them

on:
  push:
    branches: [ "langdale" ]
  pull_request:
    branches: [ "langdale" ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get current commit hash
      run: |
        export git_hash=$(git rev-parse "$GITHUB_SHA")
        echo "Used git checkout $git_hash"
    - 
      name: Build Dockerfile.yocto
      run: |
        docker build . --file Dockerfile.yocto --tag knallwinkel/yocto_langdale:latest
    -
      name: Build Dockerfile.SpotyPee
      run: |
        docker build . --file Dockerfile.SpotyPee --build-arg SPOTYPEE_LABEL=$git_hash --tag knallwinkel/spotypee:langdale
