name: Build Docker Container and execute them

on:
  push:
    branches: [ "mickledore" ]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build Dockerfile.yocto and push mickledore tag

      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.yocto
        push: true
        tags: knallwinkel/yocto_mickledore:latest
    -
      name: Build Dockerfile.SpotyPee and push mickledore tag
      
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.SpotyPee
        push: true
        build-args: |
          SPOTYPEE_LABEL=kirkstone
        tags: knallwinkel/spotypee:mickledore
